package assignment2;

/**
 * The BadGun has poor quality such that at each shot, only 80% of its original
 * power can be produced (round down to the nearest integer).
 * It is a subclass of the Weapon class and only produces 80% of the original power.
 */
public class BadGun extends Weapon {

    /**
     * Constructs a new BadGun with the specified name and power level.
     *
     * @param name  the name of the bad gun
     * @param power the power level of the bad gun
     */
    public BadGun(String name, int power) {
        super(name, power);
    }

    /**
     * Shoots the gun and returns 80% of the original power (rounded down).
     *
     * @return the power generated by the weapon
     */
    @Override
    public int shoot() {
        return (int) Math.floor(super.shoot() * 0.8);
    }
}