package assignment2;

/**
 * The SuperGun can produce a boosted shot, such that the shot produces two times
 * power than the original.
 * It is a subclass of the Weapon class.
 */
public class SuperGun extends Weapon {
    private boolean isBoosted = false;

    /**
     * Constructs a new SuperGun with the specified name and power level.
     *
     * @param name  the name of the super gun
     * @param power the power level of the super gun
     */
    public SuperGun(String name, int power) {
        super(name, power);
    }

    /**
     * Boosts the gun for the next attack.
     */
    public void boost() {
        isBoosted = true;
    }

    /**
     * Shoots the gun. If boosted, the power is doubled for the attack.
     * Resets the boosting effect after the shot.
     *
     * @return the power generated by the weapon
     */
    @Override
    public int shoot() {
        if (isBoosted) {
            isBoosted = false;
            return super.shoot() * 2;
        } else {
            return super.shoot();
        }
    }
}
