package assignment2;

/**
 * The Weapon class represents any game weapon with a name and power level.
 * A weapon can be used to shoot and generate power for attacks.
 */
public class Weapon {
    private final String weaponName;
    private final int power;

    /**
     * Constructs a new Weapon with the specified name and power level.
     *
     * @param name  the name of the weapon
     * @param power the power level of the weapon
     */
    public Weapon(String name, int power) {
        this.weaponName = name;
        this.power = Math.max(0, power);
    }

    /**
     * Returns the name of the weapon.
     *
     * @return the weapon's name
     */
    public String getName() {
        return weaponName;
    }

    /**
     * Simulates shooting the weapon and returns the power generated.
     *
     * @return the power generated by the weapon
     */
    public int shoot() {
        return power;
    }
}